name: Deploy to Azure Container App on Docker Tag Push

on:
  push:
    tags:
      - 'v*'  # Triggers only when you push tags like v1, v2, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Update Azure Container App Image
      run: |
        az containerapp update \
          --name fastapi-langgraph \
          --resource-group rg-assets \
          --image ghcr.io/${{ github.repository }}:${{ github.ref_name }}
